name: GOMS CI

on:
  pull_request:
    branches: ["*"]

jobs:
  CI:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build iOS Project
        run: |
          xcodebuild build \
          -workspace GOMS-iOS-V2.xcworkspace \
          -scheme GOMS-iOS-V2 \
          -destination 'platform=iOS Simulator,name=iPhone 15'

      - name: Send Success Notification to Discord
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: CI 성공!
          description: CI가 성공적으로 완료되었습니다.
          color: 00FF00

      - name: Send Failure Notification to Discord
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: CI 실패!
          description: CI가 실패했습니다.
          color: FF0000
